// <auto-generated />
using System;
using App2.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace App2.Migrations
{
    [DbContext(typeof(ExchangeDetailContext))]
    [Migration("20220120114137_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("App2.Models.ExchangeDetail", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"), 1L, 1);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime");

                    b.Property<decimal>("Diff")
                        .HasColumnType("DECIMAL(18,5)");

                    b.Property<decimal>("DiffFormated")
                        .HasColumnType("DECIMAL(18,5)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("Rate")
                        .HasColumnType("DECIMAL(18,5)");

                    b.Property<decimal>("RateFormated")
                        .HasColumnType("DECIMAL(18,5)");

                    b.Property<DateTime>("ValidFromDate")
                        .HasColumnType("datetime");

                    b.HasKey("ID");

                    b.ToTable("ExchangeDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
